version: '3.8'

networks:
  ziqi:
    name: ${NETWORK_NAME}

services:
  ziqiflow:
    image: ${HUB}/ziqiflow:1.0.10
    container_name: ziqiflow${SUFFIX_NAME}
    restart: always
    networks:
      ziqi:
        aliases:
          - ziqiflow
    ports:
      - "18080:80"
      - "28011:29011"
    volumes:
      - ./docker_v/work:/docker_v/work
      - ./docker_v/flow/app:/docker_v/app
      - ./docker_v/flow/cache:/docker_v/cache
      - ./docker_v/flow/sessions:/docker_v/sessions
      - ./docker_v/log/flow:/var/log/flow
      - ./docker_v/log/ziqiruner:/var/log/ziqi
    environment:
      - FKey=${FKEY}
    command: ["/bin/bash", "-c", "/auto.sh && tail -f /dev/null"]        
  ziqimysql:
    image: ${HUB}/ziqi_mysql:1.0.6
    container_name: ziqimysql${SUFFIX_NAME}
    restart: always
    networks:
      ziqi:
        aliases:
          - ziqimysql
    ports:
      - "3308:3306"
    volumes:
      - ./docker_v/mysql/conf:/etc/mysql
      - ./docker_v/mysql/logs:/var/log/mysql
      - ./docker_v/mysql/data:/var/lib/mysql

  ziqimongo:
    image: ${HUB}/ziqi_mongo:1.0.15
    container_name: ziqimongo${SUFFIX_NAME}
    restart: always
    networks:
      ziqi:
        aliases:
          - ziqimongo
    ports:
      - "27019:27017"
    volumes:
      - ./docker_v/mongodb/db:/data/db
      - ./docker_v/mongodb/conf:/conf

  ziqibackup:
    image: ${HUB}/ziqi_backup:1.0.0
    container_name: ziqibackup${SUFFIX_NAME}
    restart: always
    networks:
      ziqi:
        aliases:
          - ziqibackup
    volumes:
      - ./docker_v/backup:/backup
    command: ["/bin/bash", "-c", "/crontab_sh/auto.sh && tail -f /dev/null"]

  ziqiredis:
    image: redis:6.2.14
    container_name: ziqiredis${SUFFIX_NAME}
    restart: always
    networks:
      ziqi:
        aliases:
          - ziqiredis
    ports:
      - "6381:6379"
    command: ["redis-server", "--requirepass", "ziqiredis999"]
    volumes:
      - ./docker_v/redis/data:/data